### ISSUE TITLE
Accessing proto files from dependency in multi module maven project

### ISSUE THREAD

**Issue by benjamin-lang** [os72/protoc-jar-maven-plugin#79]
Hello together,

we have a project with the following structure

parent
|
|- module A (containing the protofiles)
|- module B
|- module C 

module B and C are using the protofiles via dependency to generate the grpc/java stubs. I used the configuration options "includeMavenTypes" and "compileMavenTypes" and when i use "maven compile" it fails the generation with the folloging exception:

**Error scanning artifact: ${project_build_directory}/moduleA/target/classes java.io.FileNotFoundException ${project_build_directory}/moduleA/target/classes (Access denied)**

While using "maven package" is working as expected. Is this a bug or intended ?

os: win10
maven: 3.6
java: 1.8
protoc: 3.5.0
protobuf: 3.6.1
grpc: 1.15.1

Thanks in advance,

Greetings
Benjamin

**Comment by os72** [comment]
Could you share your project (or a stripped down version) to help demonstrate the behavior?

**Comment by XanderAtBackboneSystems** [comment]
I've got a similar case (on mac OSX) where the error isn't "access denied" but "is directory". Which might also be the actual error under windows. As i look at the path in the error message of benjamin then it is also a directory.

Looking at the source code of the protoc-jar-maven-plugin (class: ProtocJarMojo.java) in method extractProtosFromDependencies(). The code assumes that artifact.getFile() . Is a ZipFile which it probably is after running mven package. But when running compile only then it is a directory. This is probably also the case for benjamin (i hope he can confirm this). 

The simple solution would be to add code that checks whether the path is a file or a directory so that both situations is handled properly. I never developed maven plugins so i don't know whether this is the route to take.

I hope this helps

best regards 

Xander

**Comment by XanderAtBackboneSystems** [comment]
I coded a solution (Which i was not able to test yet) see here: https://github.com/os72/protoc-jar-maven-plugin/pull/82

**Comment by os72** [comment]
@XanderAtBackboneSystems , thank you, were you able to test in the meantime?

**Comment by XanderAtBackboneSystems** [comment]
hi @os72,
Yes i was and i found one tiny bug. Unfortunately i wasn't able to find out how to run the junit tests so i used skiptest... Hope you will be able to merge  :) It would also be nice if @benjamin-lang can confirm whether is problem is solved with my pr as well...

best regards 
Xander

**Comment by benjamin-lang** [comment]
@XanderAtBackboneSystems I will try to verify it this week, as soon as I get the time.

**Comment by benjamin-lang** [comment]
@XanderAtBackboneSystems I tried with your PR in our project and mvn compile works as expected, nice and thanks :)

**Comment by os72** [comment]
@benjamin-lang, @XanderAtBackboneSystems, could you give branch `UnpackagedDependencies` a quick try? I took the PR and made a small refactoring
https://github.com/os72/protoc-jar-maven-plugin/tree/UnpackagedDependencies

(Ideally there would be a test for this; see https://github.com/os72/protoc-jar-maven-plugin/tree/master/src/test/projects)

**Comment by os72** [comment]
Released v3.11.1
